version: '3.8'
services:
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb # give your container a name
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # set your container root username
      - MONGO_INITDB_ROOT_PASSWORD=secret # set your container root password
    volumes:
      - ./database-data:/data/db
    ports:
      - '27017-27019:27017-27019'

  # Mongo Express Service
  mongo-express:
    image: mongo-express:latest # latest image
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
      # use the name of the mongo container above for server env var.
      # In our case this is mongodb

  adminer:
    image: adminer:latest # latest image
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8082:8082
